### ISSUE TITLE
Da riguardare

### ISSUE THREAD

**Issue by AndreP-git** [reticalcolatori/esercitazione2#1]
1) Il metodo esegui() del MultiplePutClient.c deve essere messo dentro al main per evitare la chiamata della funzione (orribile ma necessario)
2) Nel controllo argomenti del MainServer.c se l'utente passa una porta negativa?
3) La classe FileMonitor.c è assolutamente necessaria? Non esiste un altro modo per effettuare gli stessi controlli senza istanziare una struttura del genere?

**Comment by bartn8** [comment]
Risolto il punto 1.
Risolto il punto 2.
Il punto 3 è da pensare bene.
